export const data = [
  {
    category: "general_knowledge",
    id: "6463395501d576cfac3aa34c",
    question: "What is the name for the undersurface of a foot?",
    type: "text_choice",
    difficulty: "medium",
    correctAnswer: "Sole",
    incorrectAnswers: ["Heel", "Arch", "Instep"],
    tags: ["medicine", "anatomy", "general_knowledge"],
  },
  {
    category: "general_knowledge",
    id: "622a1c357cc59eab6f94fd80",
    question: "Who Was Responsible For The Assassination Of John Lennon?",
    type: "text_choice",
    difficulty: "hard",
    correctAnswer: "Mark David Chapman",
    incorrectAnswers: [
      "J. D. Salinger",
      "Lee Harvey Oswald",
      "John Wilkes Booth",
    ],
    tags: ["people", "the_beatles", "events", "general_knowledge"],
  },
  {
    category: "general_knowledge",
    id: "64730798cf09068746f6377c",
    question:
      "What is the verb that means to shorten a word or phrase by omitting letters?",
    type: "text_choice",
    difficulty: "easy",
    correctAnswer: "Abbreviate",
    incorrectAnswers: ["Abolish", "Abduct", "Abhor"],
    tags: ["vocabulary", "grammar", "words", "language", "general_knowledge"],
  },
  {
    category: "general_knowledge",
    id: "622a1c357cc59eab6f94fc8f",
    question: "Which word is defined as 'askew'?",
    type: "text_choice",
    difficulty: "hard",
    correctAnswer: "Cattywampus",
    incorrectAnswers: ["Funambulist", "Donkey Engine", "Widdershins"],
    tags: ["words", "general_knowledge"],
  },
  {
    category: "general_knowledge",
    id: "622a1c357cc59eab6f94fc61",
    question:
      "Which word is defined as 'a small shoot growing from the root of a plant'?",
    type: "text_choice",
    difficulty: "hard",
    correctAnswer: "Ratoon",
    incorrectAnswers: ["Curmudgeon", "Tittynope", "Fudgel"],
    tags: ["words", "general_knowledge"],
  },
  {
    category: "general_knowledge",
    id: "622a1c3d7cc59eab6f951c5d",
    question:
      "In 1968 Which British Coin Was Introduced To Replace The Ten Shilling Note?",
    type: "text_choice",
    difficulty: "hard",
    correctAnswer: "50 Pence",
    incorrectAnswers: ["£2", "20 Pence", "15 Pence"],
    tags: ["general_knowledge"],
  },
  {
    category: "general_knowledge",
    id: "622a1c357cc59eab6f94fc4e",
    question:
      "Which word is defined as 'delusion of a person who believes himself changed into an animal'?",
    type: "text_choice",
    difficulty: "medium",
    correctAnswer: "Zoanthropy",
    incorrectAnswers: ["Bobsy-die", "Agastopia", "Halfpace"],
    tags: ["words", "general_knowledge"],
  },
  {
    category: "general_knowledge",
    id: "6239f8351bb3145a698af015",
    question:
      "What word is used in the NATO Phonetic Alphabet for the letter T?",
    type: "text_choice",
    difficulty: "medium",
    correctAnswer: "Tango",
    incorrectAnswers: ["Treat", "Turn", "Tumble"],
    tags: ["general_knowledge"],
  },
  {
    category: "general_knowledge",
    id: "645cb16b7d263fd5097043cc",
    question:
      "What term is used to describe the process of preparing wool fibers before they are spun?",
    type: "text_choice",
    difficulty: "hard",
    correctAnswer: "Carded",
    incorrectAnswers: ["Combed", "Washed", "Sheared"],
    tags: ["textiles", "fashion"],
  },
  {
    category: "general_knowledge",
    id: "622a1c357cc59eab6f94fc77",
    question:
      "Which word is defined as 'a platform of a staircase where the stair turns back in exactly the reverse direction of the lower flight'?",
    type: "text_choice",
    difficulty: "hard",
    correctAnswer: "Halfpace",
    incorrectAnswers: ["Yarborough", "Erf", "Bobsy-die"],
    tags: ["words", "general_knowledge"],
  },
];
